export const OpenEnded = [
    'What\'s on your mind?',
    'How are you doing?',
    'How are you feeling?',
    'Talk to me.',
    'What\'s up?',
    'How\'s it going?',
    'Jump right in.',
    'How\'s today?',
    'What\'s happening?',
    'Tell me what\'s on your mind.',
    'What do you have to share today?',
    'What did you do today?',
    'How are you?',
    'What are you thinking?',
    'What\'s new?',
    'What\'s new today?',
    'How\'s the day going?',
    'How are you doing right now?',
    'What\'s on your mind right now?',
    'What\'s good?',
    'What made you laugh today?',
];

export const MainPrompts = [
    'What made you proud today?',
    'What did you dream about last night?',
    'What made you smile today?',
    'What did you do for someone you care about today?',
    'Did you feel empathetic today?',
    'Did you feel hopeful today?',
    'What makes you happy?',
    'What do you most want right now?',
    'Whose lives did you affect today?',
    'Give yourself a pep talk.',
    'Who are you grateful for today?',
    'What are you grateful for today?',
    'Share three things you\'re grateful for.',
    'What advice would you give yourself?',
    'What makes you feel alive?',
    'What\'s a challenge you\'re facing currently?',
    'What would a friend say to reassure you?',
    'How could you give yourself some credit?',
    'When are you courageous?',
    'What are 3 things you want to congratulate yourself on?',
    'What are 3 positive traits other people see in you?',
    'What are 3 compliments you receive on a regular basis?',
    'Tell me 3 things you\'re good at.',
    'What are 3 things that make you laugh?',
    'Share 3 things that excite you about the future.',
    'What\'s your perfect pizza?',
    'What shape is your life?',
    'What are the three possessions you can\'t live without?',
    'What are your Sunday rituals?',
    'In which ways does the full moon affect your behavior?',
    'What are your favorite smells?',
    'Have you had any telepathic or paranormal experiences?',
    'What beauty tricks do you perform to make yourself look "better"?',
    'What\'s the last compliment you gave?',
    'What are 3 extravagant things you\'d buy if you had unlimited funds?',
    'What color do you feel like right now?',
    'What\'s your pet peeve?',
    'What goes through your head when you\'re on telephone hold?',
    'Which pieces of modern technology have most shaped you?',
    'What food is always left in your refrigerator after everything else is gone?',
    'Tell me about an epic prank you\'ve pulled off.',
    'Sing to me.',
    'Which superhero(ine) do you relate to?',
    'What are three ideas you disagree with?',
    'Do any animals scare you?',
    'Tell me about your typical daydreams.',
    'What are the best gifts you\'ve been given?',
    'I always sleep facing...',
    'Tell me the names you\'ve been called, endearing and not so.',
    'What goes through your mind before you go to sleep?',
    'What do you wish when you blew out your birthday candles?',
    'What\'s under your kitchen sink?',
    'What do you do between turning off the alarm and walking out the front door?',
    'List all the modes of transportation you\'ve ever taken',
    'What are 10 regular daily items you wish you never had to buy again',
    'What are all the greetings you\'ve ever used to answer your telephone?',
    'What is something you could leave behind?',
    'What motivates you?',
    'How do you know if you\'ve been successful?',
    'What do you find beautiful?',
    'Who do you admire?',
    'What scares you?',
    'Share a memory you don\'t want to forget.',
    'What would you do today if you had more time?',
    'Tell me one of your favorite memories.',
    'What do you want to learn?',
    'What did you enjoy when you were a kid?',
    'Tell me about the things that slow you down.',
    'What thought patterns aren\'t helping you?',
    'What is a dream that hasn\'t come true yet?',
    'What\'s worrying you? Get it off your chest.',
    'Do you feel stressed today? Talk it off.',
    'What are your top 3 sources of strength?',
    'How can the people around you help?',
    'Think of a challenge you\'re facing. What\'s the first step?',
    'What\'s one thing you can do to make yourself happy right now?',
    'What\'s a nice thing someone did for you today?',
    'What 3 things are you grateful for today?',
    'Who would you be unable to live without?',
    'What sounds can you hear right now?',
    'What smell do you love smelling the most?',
    'Which emotion is your favorite to experience?',
    'What have you learned from unpleasant emotions?',
    'What is your favorite physical trait?',
    'Who was the last person you hugged?',
    'What opportunities have changed your life?',
    'What character traits are you happy to have?',
    'What luxury are you lucky to have access to?',
    'What inspires you to keep going when it\'s hard?',
    'How does it feel to eat a really great meal?',
    'When did you last feel really cozy?',
    'When did you last look up at the stars?',
    'How does it feel to give a gift?',
    'When were you last encouraged?',
    'How do you feel in moments spent alone?',
    'How does a good night\'s sleep feel?',
    'Do you tend to remember your dreams?',
    'Do you life dream or sleep dream?',
    'Describe a recurring dream you have.',
    'If you could change one thing about your dreams, what would it be?',
    'The purpose of dreaming is...',
    'The purpose of night dreaming is...',
    'The purpose of day dreaming is...',
    'What\'s a nice thing you did for someone today?',
    'What\'s one kind thing you could do for yourself right now?',
    'How could you show kindness to someone today?',
    'Who could you show kindness to today?',
    'What\'s a small way you can help someone today?',
    'Who\'s in need around you?',
    'What\'s a cause you care about?',
    'How do you think people feel when you do something kind for them?',
    'What would life be like if someone didn\'t help you out today?',
    'How does it make you feel to give a compliment?',
    'How does it make you feel to get a compliment?',
    'What will you regret not having done?',
    'What would your 90 year old self wish you did today?',
    'Are you into aliens?',
    'Do you follow any diets?',
    'What are your top 3 movies?',
    'Do you play any sports?',
    'What are your top 3 books?',
    'How many cookies have you eaten in one sitting?',
    'Where have you traveled?',
    'Do you believe in life after love?',
    'Can you dance?',
    'Vanilla or chocolate?',
    'Why is the sky blue?',
    'What\'s your favorite color?',
    'Are you a morning person or a night owl?',
    'Do you have a best friend?',
    'What\'s the last thing you\'ve created?',
    'What\'s your favorite dinosaur?',
    'What\'s your favorite sea creature?',
    'Can you swim?',
    'Where do you want to travel?',
    'What are the last 3 things you felt proud of?',
    'Who do you look up to?',
    'Has someone done it before?',
    'Who could mentor you?',
    'Do you want to be an expert at something?',
    'Are you an expert at something?',
    'Who can inspire you daily?',
    'What\'s the best case scenario?',
    'Who is helping you?',
    'Put me down and go on a micro adventure.',
    'What games did you play as a kid?',
    'What does joy feel like in your body?',
    'What color is joy?',
    'Who\'s the happiest person you know?',
    'Who\'s the most joyful person you know?',
    'What habit isn\'t serving your happiness?',
    'Show some kindness to yourself right now.',
    'What do you do to take care of yourself?',
    'Who inspires you to be more kind?',
    'What prevents you from being kind?',
    'What triggers you to be unkind?',
    'Tell me about an object that brings a smile to your face.',
    'Tell me about a time you listened to your gut.',
    'Tell me about a time you ilstened to your intuition.',
    'Where do you feel mistrust in your body?',
    'Describe what intuition means to you today.',
    'Intuitively tell me something.',
    'Start talking without thinking.',
    'Let yourself do something new today.',
    'Listen...what do YOU want to do right now?',
    'Who censors you?',
    'What censors you?',
    'What is art?',
    'Do you consider yourself an "artist"?',
    'What would you need to do to consider yourself an artist?',
    'What makes you you?',
    'How would your best friend describe you?',
    'Describe your morning today.',
    'What\'s your happy place?',
    'What\'s your favorite time of day?',
    'When\'s the last time you spent time outside?',
    'Ready set go!',
    'Find something beautiful and tell me about it.',
    'Do something beautiful for someone today.',
];

export const Creativity = [
    'Go outside',
    'Into the impossible',
    'Simple subtraction',
    'A line has two sides',
    'Accept advice',
    'A set of disconnected events',
    'Be extravagant',
    'Breathe more deeply',
    'Always the first steps',
    'Back up a few steps',
    'Bridges - build - burn',
    'Get specific',
    'Get ambigious',
    'Consult another source',
    'Destroy the most important thing',
    'Disconnect from desire',
    'Discover your formulas and abandon them',
    'Display your talent',
    'Distort time',
    'Dont avoid what is easy',
    'Humanize it',
    'Instead of changing the thing, change the world around it',
    'Assume positive intent',
    'Pay attention to the details',
    'Pay attention to distractions',
    'Blank space',
    'Remove a restriction',
    'Retrace your steps',
    'Shut the door and listen to the outside',
    'State the problem in words as clearly as possible',
    'Add some mystery',
    'Think outside the work',
    'Be unqualified for a while',
    'Voice your suspicions',
    'What are you really thinking about just now',
    'Find the edge',
    'Don\'t be flightened of chiches',
    'Give yourself some credit',
    'Abandon desire',
    'Look into the center',
    'Read the instructions',
    'Adding on',
    'All that happens is good',
    'You are more than your personality',
    'Be less ciritical more often',
    'Call your mother and ask her what to do',
    'Sing',
    'Speak',
    'Consider a transition',
    'Use an anchor',
    'Define a safe area',
    'Do the last thing',
    'Faced with a choice, do both',
    'First work alone, then work in unusual pairs',
    'From nothing to more than nothing',
    'Give way to your worst impulse',
    'Go inside',
    'Shut the door',
    'Go to an extreme',
    'Show and tell',
    'Your mistake as hidden intention',
    'Explain it to your parents',
    'Humility of intentions',
    'Simple glee',
    'Imagine a caterpillar moving',
    'Imagine the music as a moving chain',
    'What about the style',
    'Do whats approprate',
    'Something is missing',
    'It is simply a matter of work',
    'Center',
    'Live long and prosper',
    'List the qualities it has',
    'Listen in total darkness',
    'Listen in a large room, very quietly',
    'Look closely',
    'Magnify the most difficult part',
    'Make it more sensual',
    'Give an example',
    'Start on a blank page',
    'Make it more human',
    'Only a part, not the whole',
    'Remove the middle, extend the edges',
    'Steal a solution',
    'Talk a walk and study the architecture',
    'Something about pools',
    'Remove the important parts',
    'Tape your mouth',
    'Try faking it',
    'Use an unacceptable color',
    'Use cliches',
    'Use sonething as a model',
    'Use your own ideas',
    'Flip it upside down',
    'Pineapple',
    'Remember the context',
    'Try a simple solution',
    'Be impressed',
    'Go learn something',
];

export const BehavioralHealth = [
    'How can the people around you help?',
    'What\'s worrying you? Get it off your chest.',
    'What did you make today?',
    'Are you feeling isolated?',
    'Are you feeling scared or anxious about anything?',
    'What\'s bothering you?',
    'How connected are you?',
    'How are you sleeping?',
    'Did you go on a walk?',
    'Do you have kids and how are they doing with this?',
    'How different is this environment than the one you\'re used to?',
    'How do you feel about change?',
    'What do you need to change about your routine?',
];

export const Careers = [
    'What would make you excited to get up and go to work each morning?',
    'Tell me about an accomplishment in your career you\'re most proud of.',
    'What type of environment would you most thrive in?',
    'Tell me about a difficult situation you\'ve faced, how you overcame it, and what you\'d do differently if faced with it again.',
    'What could I provide to help you with your job search?',
    'How do you feel about looking for a job right now?',
    'Tell me what your dream job would be.',
    'How do you feel about talking to people and helping them all day at your job?',
    'What do you think about driving and dealing with traffic as part of your job?',
    'Tell me what type of manager or boss you most prefer to work with.',
    'What have your co-workers said about working with you?',
    'What are your top strengths at work?',
    'What type of things do you struggle with at work?',
    'Tell me how you feel about working remotely or from home.',
    'Please share how you feel about interviewing on video call.',
    'Are you worried about anything related to your job search?',
    'What type of things have you most enjoyed about previous jobs?',
    'What type of things do you want to avoid in your new job?',
    'Tell me about the best boss you have ever had and what made them great.',
    'How do you feel about working as part of a team?',
    'How do feel about working independently?',
    'Based on past interviews, what feedback did you receive?',
    'Are you looking to advance your career, stay at the same level or take a step back from responisbility?',
];

export const Coaching = [
    'How do you feel about your goal?',
    'Do you feel supported?',
    'Do you need any resources?',
    'Is anything blocking you?',
    'Is there anything that would accelerate your efforts?',
    'What\'s the latest with your goal?',
    'How will others benefit from you achieving your goal?',
    'What can you do this week to make progress on your goal?',
    'How will you personally benefit from acheaving your goal?',
    'Do you think this goal will help grow the company?',
    'Does your goal personally motivate you?',
    'How is today going for you?',
    'What progress did you make on your goal?',
    'What unplanned leadership challenge did you face today?',
    'What assumptions did you make today?',
    'Did you ask powerful questions?',
    'How present were you today, and what was the major contributor?',
    'What assumptions about someone did you find yourself making today?',
    'What was a moment today that you found yourself unable to "Welcome Everything"?',
    'In the last few days, what\'s one time you found yourself trying to balance your needs, with the needs of others?',
    'What\'s keeping you from being more present?',
    'Describe a time in the past week where you were able to practice being a more emergent leader.',
    'How have you benefited from being more present?',
    'How did you judge yourself today?',
    'What\'s important to you right now?',
    'What powerful questions did you ask today?',
    'How is your listening practice going?',
    'Did you catch yourself listening to be heard, rather than listening to understand?',
    'Where are your open-ended questions opening the conversations?',
    'What\'s a win you can share on practing powerful questions?',
    'How is your practice of asking open-ended questions going?',
    'What do you find yourself optimizing for right now?',
    'What\'s the loudest voice saying in your mind right now?',
    'What are you grateful for today?',
    'What did you do today that you are proud of?',
    'How grounded do you feel right now?',
    'Where are you on a spectrum of focused to distracted?',
    'What do you most want right now?',
    'Whose lives did you affect today?',
    'How could you give yourself some credit?',
    'Give yourself a pep talk.',
    'What are 3 things you\'re grateful for?',
    'What\'s your energy level right now?',
    'On a scale of very calm to very anxious, where are you right now?',
    'What emotion are you most present to right now?',
    'What\'s the last thing that inspired you to action?',
    'Where do you influence a decision today?',
    'Where did you feel a sense of agency in your leadership today?',
    'What stories are you telling yourself?',
    'Did you use a conversation starter recently?',
    'How has the delta between facts and stories helped you as a leader?',
    'What have you chosen to adapt to or accept recently?',
    'What steps can you take if you feel out of control?',
    'Do you ever enlist allies to help you influence a situation?',
    'What\'s the last time you were aware of being triggered?',
    'What are the facts and what are the assumptions in a recent situation?',
    'What missing data do you need to really understand a situation?',
    'What part did you play in a recent situation?',
    'What is your intention in discussing the story you\'re telling yourself with another person?',
    'How did it feel after you validated the truth (or not) of your take on a situation?',
    'If you can\'t control a situation, how can you influence it?',
    'If you can\'t control or influeince a situation, are you willing to adapt to it or accept it?',
    'Where do you draw the line in the sand - you\'re not willing to adapt to it or accept it?',
    'If you feel out of control, what\'s way for you to still lead powerfully?',
    'Where can you gain a sense of power even if something feels like it\'s being done to you?',
    'What have you done recently to make sure your team feels safe to voice their opinions?',
    'What have you forgiven yourself for lately?',
    'What do you need to feel safe to voice your opinions?',
    'When someone makes a mistake on your team, how do you handle it?',
    'When you make a mistake, how do you handle it?',
    'When ideating/brainstorming, what happens when someone comes up with an idea that is really out there?',
    'Do you feel safe taking risks?',
    'How comfortable are you asking for help?',
    'Does your team feel comfortable asking others for help?',
    'Are you and your team able to bring up tough issues?',
    'When giving feedback, do you balance asking questions and stating your opinions?',
    'Do you tend to ask for permission or forgivness?',
    'When problem solving do you ask for input and then decide or state your opinion and ask for dissent?',
    'How do you stay curious during hard conversations?',
    'What happens in meetings when nobody has much input?',
    'What happens in meetings with one person tries to dominate the discussion?',
    'How do you stay grounded enough in hard conversations that you can still stay curious?',
    'What\'s an example of when new information changed your opinion?',
    'How do you feel when someone dictates to you, versus discussing with you?',
    'How do you know when it\'s time to make a decision after getting everyone\'s input?',
    'How have you been balancing your team health goals with your team\'s delivery goals?',
    'In team conversations, how are you resolving short term and long term goal conflicts?',
    'What are your personal, or team goals that most frustrate you, and why?',
    'What conflicting goals have you come across when working with other groups? Why are they conflicting?',
    'Is there a goal-conflict resolution you want to celebrate? What was it and how did you resolve it?',
    'What\'s the goal you are stuck on? and why?',
    'What\'s your default reaction when you learn your team\'s goal is in conflict with another team?',
    'Have you been more present to the information you share with other people?',
    'In general, do you tend to share too little or too much information with others? If it depends, what are the circumstances?',
    'During team problem solving,  how do you get each memeber to share information that\'s unique to them?',
    'How do you feel when someone is talking about something you are already familiar with?',
    'How do you feel when someone is talking about something you are unfamiliar or don\'t know anything about?',
    'How can you combat Information Sharing Bias with your team conversations?',
    'In past conversations, how have you judged colleagues for bringing seemingly irrelevant infomation into the conversation?',
    'What\'s a group decision technique you\'ve used recently?',
    'What new approaches to group decision making have you considered?',
    'What emotions do you feel when you are unable to get your team aligned on a go forward path?',
    'What\'s a recent group discussion you found yourself avoiding because it would take too long to get alignment?',
    'In team discussion, do you notice who are the fast and slow thinkers?',
    'In team discussions, do you intervene when you notice only a small group of voices are being heard?',
    'In your role, what conflicting goals are you most present to?',
    'What\'s one goal that you have which is in conflict with another group\'s goal? Have you surfaced the conflict?',
    'What are some benefits of having goals that conflict with one another?',
    'Name a missed opportunity to share information with a teammate to help them solve a problem? How did you feel when you discovered the miss?',
    'When sharing information to your team for visiblity, do you tend to overshare, or understare the information?',
    'What\'s your default reaction when a group decision seems to be in a stalemate?',
    'What\'s a decision you\'ve made recently as a leader that could have been improved by a group decision process?',
    'In a recent group decision process, how have you set context?',
];
